/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

#ifndef _SVC_STRINGTYPES_H
#define _SVC_STRINGTYPES_H

// Here, you look like you're in need of some error codes.
namespace SvcStrCnv {
  typedef enum {
    // The conversion failed for some generic 'fatal' reason, not covered by the
    // other reasons below.  (Possibly a bug in the service implementation).
    ERROR_FATAL = -1,

    // The conversion failed because your output buffer was too small.
    ERROR_BUFFER_OVERRUN = -2,

    // The conversion failed because your input string had unrecoverable errors in it
    ERROR_INPUT = -3,

    // The service instance does not support that type of encoding for conversion
    ERROR_INVALID = -4,

    // The service instance isn't available (ONLY generated by EncodedStr.cpp, obviously)
    ERROR_UNAVAILABLE = -5,

  } ConvertErrors;

  // These types MUST be supported by the platform port for this service.
  typedef enum {
    OSNATIVE='natv',
    UTF16='u-16'
  } EncodingTypes;
  // Other service instances may implement other encoding types.
  // They all should provide their own FOURCC #define or enum in their headers.
}


#endif // _SVC_STRINGTYPES_H
