/*

  Nullsoft WASABI Source File License

  Copyright 1999-2001 Nullsoft, Inc.

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    3. This notice may not be removed or altered from any source distribution.


  Brennan Underwood
  brennan@nullsoft.com

*/

/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __C_BROWSER_H
#define __C_BROWSER_H

#include "c_guiobject.h"

#define C_BROWSER_PARENT C_GuiObject

class COMEXP C_Browser : public C_BROWSER_PARENT {
  public:

  C_Browser(ScriptObject *object);
  C_Browser();
  virtual ~C_Browser();

  virtual void C_hook(ScriptObject *o);

  ScriptObject *getScriptObject();

  virtual void navigateUrl(const char *url);
  virtual void back();
  virtual void forward();
  virtual void stop();
  virtual void refresh();
  virtual void home();
  virtual void setTargetName(const char *targetname);
  virtual int onBeforeNavigate(const char *url, int flags, const char *targetframename);
  virtual void onDocumentComplete(const char *url);

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int navigateurl_id;
  static int back_id;
  static int forward_id;
  static int stop_id;
  static int refresh_id;
  static int home_id;
  static int settargetname_id;
  static int onbeforenavigate_id;
  static int ondocumentcomplete_id;
};

#endif
